name: Auto Merge to Main

on:
  push:
    branches:
      - dev-marco
      - dev-martinsinner
      - Emrah-Branch
      - ci-cd
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Configure Git
        run: |
          git config user.name "Auto-Merge[Bot]"
          git config user.email "noreply@github.com"
      
      - name: Fetch source branch
        run: |
          git fetch origin ${{ github.ref }}

      - name: Merge source branch into main
        run: |
          git merge origin/${{ github.ref_name }}

      - name: Push changes to main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} main
          